### ISSUE TITLE
Failed upsert?

### ISSUE THREAD

**Issue by will-weiss** [morehumaninternet/roar-server#35]
Haven't checked if we're seeing this on production, but seeing this locally if visiting a website with no twitter handle

```
Error: Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query.  Columns: twitter_handle.
    at QueryCompiler_PG._prepUpdate (/Users/willweiss/dev/morehumaninternet/roar-server/node_modules/knex/lib/query/compiler.js:819:13)
    at QueryCompiler_PG.update (/Users/willweiss/dev/morehumaninternet/roar-server/node_modules/knex/lib/dialects/postgres/query/compiler.js:36:29)
    at QueryCompiler_PG.toSQL (/Users/willweiss/dev/morehumaninternet/roar-server/node_modules/knex/lib/query/compiler.js:61:29)
    at Formatter.unwrapRaw (/Users/willweiss/dev/morehumaninternet/roar-server/node_modules/knex/lib/formatter.js:133:48)
    at Formatter.parameter (/Users/willweiss/dev/morehumaninternet/roar-server/node_modules/knex/lib/formatter.js:127:17)
    at /Users/willweiss/dev/morehumaninternet/roar-server/node_modules/knex/lib/raw.js:133:22
    at String.replace (<anonymous>)
    at replaceRawArrBindings (/Users/willweiss/dev/morehumaninternet/roar-server/node_modules/knex/lib/raw.js:123:23)
    at Raw.toSQL (/Users/willweiss/dev/morehumaninternet/roar-server/node_modules/knex/lib/raw.js:74:13)
    at /Users/willweiss/dev/morehumaninternet/roar-server/node_modules/knex/lib/runner.js:31:36
    at /Users/willweiss/dev/morehumaninternet/roar-server/node_modules/knex/lib/runner.js:277:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

This could be the culprit

```typescript
export function upsertWebsite(object: { domain: string, twitter_handle: null | string }): Promise<Website> {
  if (object.domain.startsWith('www.')) {
    throw new Error('Strip www. before creating the website')
  }

  if (object.twitter_handle && !object.twitter_handle.startsWith('@')) {
    throw new Error('Twitter handle must start with a @')
  }

  return upsert({ db, table: 'websites', object, key: 'domain' })
}
```

**Comment by will-weiss** [comment]
Closing for now as we now `await` this operation, so we should see server errors instead of this failing silently
